### PR TITLE
Re-Added Navigationbar

### PR DESCRIPTION
**Pull request by HenrijetteOest**
Re added the navigationbar in  _Layout.cshtml, path is : ChirpWeb, Pages, Shared, _Layout.cshtml

### CODE REVIEW

**Review by Thyme-Cat — APPROVED** [review]
lgtm, we the login peeps will look closer at the warning.

**Review by llsa-itu — APPROVED** [review]
lgtm

**Review by tomat-suppe — APPROVED** [review]
slayy queens, looks good

**Review by JaSNOHo — APPROVED** [review]
lgtm

**Pull request merged**
