### PR TITLE
Onion architecture implemented and EF Core foundation added

### PR DESCRIPTION
**Pull request by tomat-suppe**
This is the fixed pull request #92.

We have restructured the entire folder structure to follow the principle of onion architecture.
We have updated namespaces etc. so that all files can find each other.
We have laid the foundation for an EF Core implementation but still need to fix CheepService and DBFacade classes.

Co-authored-by: Sophie Gabriela [slak@itu.dk](mailto:slak@itu.dk)
Co-authored-by: Jasmin [jsho@itu.dk](mailto:jsho@itu.dk)
Co-authored-by: Maria [arnv@itu.dk](mailto:arnv@itu.dk)
Co-authored-by: Henriette [hoes@itu.dk](mailto:hoes@itu.dk)
Co-authored-by: Laura [llsa@itu.dk](mailto:llsa@itu.dk)
Co-authored-by: Group 3
Co-authored-by: ChatGPT

### CODE REVIEW

**Review by JaSNOHo — APPROVED** [review]
Very mindful

**Review by HenrijetteOest — APPROVED** [review]
lgtm

**Review by llsa-itu — APPROVED** [review]
Looks good.

**Review by Thyme-Cat — APPROVED** [review]
It looks good

**Pull request merged**
